import { ArrowDown, ArrowUpRight, Check, Code2, Compass, GitBranch, Layers3, MessageCircle, MoveUpRight, Send, ShieldCheck, Sparkles, Terminal, Timer, UserRound, Zap } from 'lucide-react';
import Header, { Brand } from '@/components/Header';
import LeadForm from '@/components/LeadForm';
import CourseButton from '@/components/CourseButton';
import { readContent } from '@/lib/db';
import { money } from '@/lib/content';
import { documentAvailable, leadsReady } from '@/lib/leads';
export const dynamic = 'force-dynamic';
const benefitIcons = [Compass, UserRound, Code2, MoveUpRight, ShieldCheck];
const telegramProps = { target: '_blank', rel: 'noopener noreferrer' };
function SectionLabel({ n, children }: { n: string; children: React.ReactNode }) { return <div className="section-label"><span>{n}</span>{children}</div>; }
export default async function Home({ searchParams }: { searchParams: Promise<{ course?: string }> }) {
  const { content: c } = readContent();
  const selected = (await searchParams).course;
  const initialCourse = c.courses.some(course => course.id === selected) ? selected! : 'undecided';
  return <><a className="skip-link" href="#main">Перейти к содержимому</a><Header /><main id="main">
    <section className="hero" id="home"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" />{c.hero.eyebrow}</div><h1>{c.hero.title}</h1><p className="hero-motto">{c.hero.subtitle}</p><p className="hero-description">{c.hero.description}</p><div className="hero-actions"><a href="#courses" className="button">Выбрать своё направление <ArrowUpRight size={20} /></a><a href={c.contacts.telegram} {...telegramProps} className="text-link">Написать в Telegram <ArrowUpRight size={17} /></a></div><div className="hero-meta"><span><Check size={15} /> Можно с нуля</span><span><Check size={15} /> С поддержкой наставника</span></div>{c.promotion && <p className="promotion"><Sparkles size={18} />{c.promotion}</p>}</div>
      <div className="hero-art" aria-hidden="true"><div className="art-grid" /><div className="art-caption">YOUR NEXT CHAPTER <span>→ IT</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-core"><span>&lt;</span><i>/</i><span>&gt;</span></div><div className="floating-card code-card"><div className="code-card-top"><div className="window-dots"><i /><i /><i /></div><span>first_step.py</span><Terminal size={14} /></div><div className="code-lines"><span className="line-number">01</span><span><em>def</em> create_future():</span><span className="line-number">02</span><span> &nbsp; skills = <b>"practice"</b></span><span className="line-number">03</span><span> &nbsp; <em>return</em> your_next_step</span></div><div className="code-result"><span /> Готово к новому началу</div></div><div className="floating-card practice-card"><div className="practice-icon"><GitBranch size={22} /></div><div><strong>От знаний к практике</strong><small>Ваш путь начинается здесь</small></div><ArrowUpRight size={19} /></div><div className="art-bottom"><span>PYTHON</span><span className="art-plus">+</span><span>QUALITY ASSURANCE</span></div></div>
    </div><div className="container hero-bottom"><span>Практическое обучение. Человеческая поддержка.</span><a href="#benefits">Знакомьтесь с KaleaDoSkill <ArrowDown size={15} /></a></div></section>
    <section className="benefits section" id="benefits"><div className="container"><SectionLabel n="01">УЧИТЬСЯ С УВЕРЕННОСТЬЮ</SectionLabel><div className="section-heading"><h2>Большая цель.<br /><span className="muted-heading">Понятные шаги.</span></h2><p>Практическое обучение программированию и востребованным IT-навыкам: от первых шагов до уверенных знаний.</p></div><div className="benefit-grid">{c.benefits.map((b, i) => { const Icon = benefitIcons[i % benefitIcons.length]; return <article className="benefit-card" key={i}><div className="benefit-top"><Icon size={25} strokeWidth={1.5} /><span>0{i + 1}</span></div><h3>{b.title}</h3><p>{b.description}</p></article>; })}</div></div></section>
    <section className="courses section" id="courses"><div className="container"><SectionLabel n="02">ВАШЕ НАПРАВЛЕНИЕ</SectionLabel><div className="section-heading"><h2>Новая профессия<br />начинается с выбора.</h2><p>Выберите то, что вам интересно.<br />Мы поможем сделать первый шаг.</p></div><div className="course-grid">{c.courses.map((course, i) => <article className={`course-card ${i % 2 ? 'course-qa' : 'course-python'}`} key={course.id}><div className="course-top"><span className="course-tag">{course.label}</span><span className="course-symbol" aria-hidden="true">{i % 2 ? <ShieldCheck size={44} strokeWidth={1.2} /> : <Code2 size={44} strokeWidth={1.2} />}</span></div><div className="course-duration"><Timer size={15} />{course.duration}<span>Ориентировочно</span></div><h3>{course.title}</h3><p className="course-description">{course.description}</p><div className="course-divider" /><h4>ЧЕМУ ВЫ НАУЧИТЕСЬ</h4><ul className="skills">{course.skills.map(skill => <li key={skill}><Check size={16} />{skill}</li>)}</ul><div className="course-project"><Layers3 size={18} />{course.project}</div><div className="course-bottom"><div className="course-price"><small>Полная стоимость</small><strong>{money(course.price)}</strong></div><CourseButton id={course.id} /></div></article>)}</div><p className="section-note"><MessageCircle size={17} /> Не знаете, что выбрать? <a href={c.contacts.telegram} {...telegramProps}>Обсудим ваши цели в Telegram <ArrowUpRight size={14} /></a></p></div></section>
    <section className="included section" id="included"><div className="container included-grid"><div><SectionLabel n="03">ВСЁ ДЛЯ ВАШЕГО СТАРТА</SectionLabel><h2>Вы учитесь.<br /><span>Мы поддерживаем.</span></h2><p className="included-description">Обучение — это больше, чем материалы.<br />Это практика, обратная связь и возможность задать вопрос, когда что-то не получается.</p><div className="notion-note"><span className="notion-mark">N</span><p><strong>Знания всегда под рукой</strong><br />Индивидуальный доступ к материалам в Notion после оформления обучения.</p></div></div><div className="included-list">{c.included.map((item, i) => <div className="included-item" key={i}><span>0{i + 1}</span><h3>{item}</h3><Check size={21} /></div>)}</div></div></section>
    <section className="payment section" id="payment"><div className="container"><SectionLabel n="04">ПРОЗРАЧНЫЕ УСЛОВИЯ</SectionLabel><div className="section-heading"><h2>Инвестиция<br />в ваши навыки.</h2><p>Полная стоимость известна заранее.<br />Доступные способы оплаты уточняем перед оформлением.</p></div><div className="payment-prices">{c.courses.map(course => <div key={course.id}><span>{course.title}</span><strong>{money(course.price)}</strong></div>)}</div><div className="payment-grid">{c.payments.map((p, i) => <article className="payment-card" key={p.id}><div className="payment-top"><span className={`bank-symbol bank-${i % 3}`}>{i % 3 === 0 ? <Check size={21} /> : i % 3 === 1 ? 'Т' : 'Я'}</span><h3>{p.name}</h3></div><p>{p.description}</p><span className="payment-status"><span />{p.status === 'available' ? 'Доступно по условиям провайдера' : p.status === 'request' ? 'Доступность уточняется' : 'Пока недоступно'}</span>{p.status === 'available' ? <a className="payment-link" href={p.url} {...telegramProps}>Перейти к провайдеру <ArrowUpRight size={16} /></a> : p.status === 'request' ? <a className="payment-link" href={c.contacts.telegram} {...telegramProps}>Уточнить условия <ArrowUpRight size={16} /></a> : <span className="payment-link disabled-text">Подключение ожидается</span>}</article>)}</div><details className="payment-details"><summary>Что важно знать о способах оплаты <span>+</span></summary><div><p>Полная оплата — сразу вся сумма. Кредит — банк финансирует покупку, возможны проценты. Рассрочка — платежи по графику, условия зависят от банка и договора. Оплата частями и Сплит — платежи по условиям сервиса, возможны комиссии и ограничения.</p><p>Срок до 36 месяцев возможен только по конкретному банковскому продукту и при одобрении банком. Перечисленные варианты не означают, что все продукты уже подключены. Онлайн-оплата на сайте пока не подключена.</p></div></details></div></section>
    <section className="manifesto"><div className="container manifesto-inner"><span className="eyebrow"><Sparkles size={15} /> ПОЧЕМУ KALEADOSKILL</span><h2>Ваши амбиции.<br /><span>Наша поддержка.</span></h2><p>Практическая готовность, индивидуальная помощь и прозрачная стоимость. Чтобы каждый новый навык становился шагом к вашей цели.</p><a className="button button-ivory" href="#apply">Сделать первый шаг <ArrowUpRight size={19} /></a><div className="manifesto-decoration" aria-hidden="true"><div /><div /><div /></div></div></section>
    <section className="faq section" id="faq"><div className="container faq-grid"><div><SectionLabel n="05">ОТВЕТЫ НА ВОПРОСЫ</SectionLabel><h2>Давайте<br />разберёмся.</h2><p>Не нашли свой вопрос?<br />Мы на связи в Telegram.</p><a className="text-link" href={c.contacts.telegram} {...telegramProps}>Задать вопрос <ArrowUpRight size={17} /></a></div><div className="faq-list">{c.faq.map((f, i) => <details key={i}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</div></div></section>
    <section className="apply section" id="apply"><div className="container apply-grid"><div className="apply-copy"><SectionLabel n="06">НАЧНЁМ С ЗНАКОМСТВА</SectionLabel><h2>Первый шаг —<br /><span>просто поговорить.</span></h2><p>Расскажите, что вам интересно.<br />Поможем выбрать направление и ответим на вопросы об обучении.</p><a className="apply-telegram" href={c.contacts.telegram} {...telegramProps}><span><Send size={22} /></span><div><strong>Удобнее в Telegram?</strong><small>Напишите нам напрямую</small></div><ArrowUpRight size={22} /></a><p className="apply-reassurance"><ShieldCheck size={17} />Без обязательств и давления</p></div><LeadForm content={c} enabled={leadsReady(c)} initialCourse={initialCourse} /></div></section>
  </main><footer className="footer" id="contacts"><div className="container"><div className="footer-main"><div><Brand footer /><p className="footer-motto">Освой IT. Создавай будущее.</p></div><div className="footer-contact"><span className="footer-label">НА СВЯЗИ</span><a className="official-telegram" href={c.contacts.telegram} {...telegramProps}>KaleaDoSkill — официальный Telegram <ArrowUpRight size={17} /></a>{c.contacts.phone && <a href={`tel:${c.contacts.phone.replace(/[^+0-9]/g, '')}`}>{c.contacts.phone}</a>}<span className="additional-label">Дополнительные контакты</span><div className="additional-contacts">{c.contacts.additional.map(a => <a key={a.url} href={a.url} {...telegramProps}>{a.label}<ArrowUpRight size={13} /></a>)}</div></div></div><div className="footer-bottom"><div>© {new Date().getFullYear()} KaleaDoSkill<br /><span>ИП Борисенко Максим Александрович · ИНН 720413627388</span></div><div className="legal-links">{[['offer', 'Оферта'], ['privacy', 'Политика обработки данных'], ['consent', 'Согласие']].map(([key, label]) => { const url = c.legal[key as keyof typeof c.legal]; return <a key={key} href={documentAvailable(url) ? url : `/legal/${key}`} {...(documentAvailable(url) ? telegramProps : {})}>{label}</a>; })}</div></div><p className="footer-disclaimer">Помощь в подготовке к карьере не является гарантией трудоустройства.</p></div></footer></>;
}
