'use client';
import { useState } from 'react';
import type { Content } from '@/lib/content';
type Tab = 'Главная' | 'Курсы' | 'Преимущества' | 'FAQ' | 'Контакты' | 'Оплата' | 'Документы';
const tabs: Tab[] = ['Главная', 'Курсы', 'Преимущества', 'FAQ', 'Контакты', 'Оплата', 'Документы'];
export default function AdminEditor({ initial, initialRevision }: { initial: Content; initialRevision: number }) {
  const [content, setContent] = useState(initial); const [revision, setRevision] = useState(initialRevision);
  const [tab, setTab] = useState<Tab>('Главная'); const [message, setMessage] = useState(''); const [error, setError] = useState(false); const [saving, setSaving] = useState(false);
  function change(mutator: (draft: Content) => void) { setContent(current => { const next = structuredClone(current); mutator(next); return next; }); setMessage(''); }
  const input = (label: string, value: string, edit: (value: string) => void, multiline = false) => <label key={label} className="form-field">{label}{multiline ? <textarea rows={3} value={value} maxLength={1500} onChange={e => edit(e.target.value)} /> : <input value={value} onChange={e => edit(e.target.value)} />}</label>;
  async function save() {
    setSaving(true); setMessage('');
    try { const r = await fetch('/api/admin/content', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content, revision }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error + (data.details?.length ? ': ' + data.details.map((d: { path: string[]; message: string }) => `${d.path.join('.')}: ${d.message}`).join('; ') : '')); setRevision(data.revision); setError(false); setMessage('Сохранено. Изменения видны на сайте после обновления страницы.'); } catch (e) { setError(true); setMessage(e instanceof Error ? e.message : 'Ошибка сети'); } finally { setSaving(false); }
  }
  async function logout() { await fetch('/api/admin/logout', { method: 'POST' }); window.location.reload(); }
  return <div className="admin-shell"><div className="admin-header"><h1>KaleaDoSkill · Контент</h1><div className="admin-actions"><a href="/" target="_blank" rel="noopener noreferrer" className="admin-secondary">Открыть сайт</a><button onClick={logout} className="admin-secondary">Выйти</button></div></div><p className="admin-help">Настройки сохраняются в базе данных сайта. Секреты здесь не показываются и задаются через окружение сервера. Сохранение проверяет данные; одновременные правки защищены проверкой версии.</p><div className="admin-tabs" role="tablist" aria-label="Разделы контента">{tabs.map(t => <button key={t} id={`tab-${t}`} role="tab" aria-selected={t === tab} aria-controls="admin-panel" onClick={() => setTab(t)}>{t}</button>)}</div><div role="tabpanel" id="admin-panel" aria-labelledby={`tab-${tab}`}>
    {tab === 'Главная' && <div className="admin-card"><h2>Первый экран и акция</h2>{Object.entries(content.hero).map(([key, value]) => input(({ eyebrow: 'Подпись', title: 'Главный заголовок', subtitle: 'Слоган', description: 'Описание' } as Record<string, string>)[key], value, v => change(d => { d.hero[key as keyof Content['hero']] = v; }), key === 'description'))}{input('Акция (пустое поле скрывает блок)', content.promotion, v => change(d => { d.promotion = v; }))}<h2>Что входит</h2>{input('Один пункт на строку', content.included.join('\n'), v => change(d => { d.included = v.split('\n'); }), true)}</div>}
    {tab === 'Курсы' && <>{content.courses.map((c, i) => <div className="admin-card" key={i}><h2>Курс {i + 1}</h2>{input('ID (латиница, цифры, дефис; уникальный)', c.id, v => change(d => { d.courses[i].id = v; }))}{input('Название', c.title, v => change(d => { d.courses[i].title = v; }))}{input('Категория', c.label, v => change(d => { d.courses[i].label = v; }))}{input('Описание', c.description, v => change(d => { d.courses[i].description = v; }), true)}<label className="form-field">Стоимость, ₽<input type="number" min={0} max={10000000} value={c.price} onChange={e => change(d => { d.courses[i].price = Number(e.target.value); })} /></label>{input('Ориентировочный срок', c.duration, v => change(d => { d.courses[i].duration = v; }))}{input('Навыки (один на строку)', c.skills.join('\n'), v => change(d => { d.courses[i].skills = v.split('\n'); }), true)}{input('Результат практики', c.project, v => change(d => { d.courses[i].project = v; }))}<button className="admin-secondary" disabled={content.courses.length === 1} onClick={() => change(d => { d.courses.splice(i, 1); })}>Удалить курс</button></div>)}<button className="admin-secondary" onClick={() => change(d => { d.courses.push({ id: `course-${Date.now()}`, title: 'Новый курс', label: 'НАПРАВЛЕНИЕ', description: 'Описание обучения', price: 0, duration: 'Уточняется', skills: ['Практические навыки'], project: 'Практический проект' }); })}>Добавить курс</button></>}
    {tab === 'Преимущества' && <>{content.benefits.map((b, i) => <div className="admin-card" key={i}>{input('Заголовок', b.title, v => change(d => { d.benefits[i].title = v; }))}{input('Описание', b.description, v => change(d => { d.benefits[i].description = v; }), true)}<button className="admin-secondary" disabled={content.benefits.length === 1} onClick={() => change(d => { d.benefits.splice(i, 1); })}>Удалить</button></div>)}<button className="admin-secondary" onClick={() => change(d => { d.benefits.push({ title: 'Преимущество', description: 'Описание' }); })}>Добавить преимущество</button></>}
    {tab === 'FAQ' && <>{content.faq.map((f, i) => <div className="admin-card" key={i}>{input('Вопрос', f.question, v => change(d => { d.faq[i].question = v; }))}{input('Ответ', f.answer, v => change(d => { d.faq[i].answer = v; }), true)}<button className="admin-secondary" disabled={content.faq.length === 1} onClick={() => change(d => { d.faq.splice(i, 1); })}>Удалить вопрос</button></div>)}<button className="admin-secondary" onClick={() => change(d => { d.faq.push({ question: 'Новый вопрос', answer: 'Ответ' }); })}>Добавить вопрос</button></>}
    {tab === 'Контакты' && <div className="admin-card"><h2>Контакты школы</h2>{input('Телефон (пустое поле скрывает телефон)', content.contacts.phone, v => change(d => { d.contacts.phone = v; }))}{input('Официальный Telegram', content.contacts.telegram, v => change(d => { d.contacts.telegram = v; }))}{content.contacts.additional.map((a, i) => <div key={i}>{input('Подпись дополнительного контакта', a.label, v => change(d => { d.contacts.additional[i].label = v; }))}{input('Telegram-ссылка', a.url, v => change(d => { d.contacts.additional[i].url = v; }))}<button className="admin-secondary" onClick={() => change(d => { d.contacts.additional.splice(i, 1); })}>Удалить контакт</button></div>)}<button className="admin-secondary" onClick={() => change(d => { d.contacts.additional.push({ label: '@contact', url: 'https://t.me/contact' }); })}>Добавить контакт</button></div>}
    {tab === 'Оплата' && <><p className="admin-warning">Активируйте только подтверждённые продукты. Ссылка ведёт на официальную страницу провайдера; сайт не создаёт платежей и не выдаёт доступ. Для API-интеграции необходимы договор, ключи, проверяемый webhook и кассовый сценарий.</p>{content.payments.map((p, i) => <div className="admin-card" key={p.id}>{input('Название', p.name, v => change(d => { d.payments[i].name = v; }))}{input('Описание', p.description, v => change(d => { d.payments[i].description = v; }), true)}<label className="form-field">Статус<select value={p.status} onChange={e => change(d => { d.payments[i].status = e.target.value as typeof p.status; })}><option value="request">Уточнить условия в Telegram</option><option value="unavailable">Недоступно</option><option value="available">Подтверждено, есть официальная ссылка</option></select></label>{input('Официальная HTTPS-ссылка (только для подтверждённого продукта)', p.url, v => change(d => { d.payments[i].url = v; }))}</div>)}</>}
    {tab === 'Документы' && <div className="admin-card"><h2>Юридические документы</h2><p className="admin-help">Текстовые версии оферты, политики и согласия уже встроены в сайт и доступны по адресам /legal/offer, /legal/privacy и /legal/consent. Ниже можно указать путь к утверждённому PDF, если владелец решит заменить соответствующую страницу файлом.</p>{input('Политика обработки данных — PDF (необязательно)', content.legal.privacy, v => change(d => { d.legal.privacy = v; }))}{input('Публичная оферта — PDF (необязательно)', content.legal.offer, v => change(d => { d.legal.offer = v; }))}{input('Согласие на обработку данных — PDF (необязательно)', content.legal.consent, v => change(d => { d.legal.consent = v; }))}<p className="admin-warning">Пример пути: /documents/privacy.pdf. Само размещение документа не заменяет проверку хранения и удаления сообщений в Telegram, локализации данных, трансграничной передачи, характера услуг, рекламы и платежей со специалистом.</p></div>}
    </div><div className="admin-actions" style={{ marginTop: 25 }}><button className="button" onClick={save} disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить изменения'}</button><span className={`admin-status ${error ? 'error' : ''}`} role="status">{message}</span></div></div>;
}
